### ISSUE TITLE
Copy only specific key from Claims/Payload

### ISSUE THREAD

**Issue by tolik518** [jwt-rs/jwt-ui#43]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to copy a specific claim, since there is no obvious way to copy only one key, its only possible to copy all at once, paste them somewhere and then copy a specific key.

**Describe the solution you'd like**
I'm not sure what the best solution here would be. One possible solution would be giving the user the possibility to iterate through the keys and copy only one key when pressing `c`.  
 
**Additional context**
When we replace old JWTs in our company we also note the JTI so it's easier to find the keys across our infrastructure - since it's easier to compare 2 JTIs than 2 JWTs. 
I would love to use jwt-ui on a daily basis, but since it's impossible to copy only one key, it doesnt really makes my workflow any easier than just using jwt.io

**Comment by deepu105** [comment]
Ya this was a tough one, enabliing mouse capture means copy by selection would not work. So its gonna be either ability to use mouse on the CLI or ability to copy a selection, please keep in mind selection is gonna work on the entire thing so you cant select two line from within claims for example, you can only select either by single line or by entire two lines of the CLI including UI elements. I think a solution I could think of is providing an option toi disble mouse capture on demand with a short cut. WDYT?

**Comment by Shivam250702** [comment]
@tolik518  I can work on this issue please assign this issue to me

**Comment by deepu105** [comment]
Feel free to work on this @Shivam250702 and @sOnU1002 , I can accept the PR with the best solution

**Comment by parthj000** [comment]
@deepu105 , I am also working on it !

**Comment by deepu105** [comment]
Fixed by adding a coomand line flag `-d` to disable mouse capture
