### ISSUE TITLE
Improving the readability of the README file.

### ISSUE THREAD

**Issue by rashi07dashore** [jwt-rs/jwt-ui#77]
Describe the solution you'd like
I would like to see a table of contents at the beginning of the README file that links to different sections. This would enhance navigation and improve the overall user experience.

Additional context
A well-structured README with a table of contents can significantly improve accessibility and user understanding, especially for new users.

**Comment by smv1256** [comment]
I'd like to work on this, please!

**Comment by deepu105** [comment]
@rashi07dashore feel free to submit a PR with the update
